#! /bin/bash

SCRIPT_PATH="~/scripts/bigtree"
START_DIR=$(pwd -LP)
GENE_LIST=$SCRIPT_PATH/gene_list.txt 
GENE_LIST_SORTED=$SCRIPT_PATH/gene_list_sorted.txt 
MIM_SEQ_LENGTH=40

LOG=$START_DIR/Log_Bigtree.txt

LOG_DIR="$START_DIR/00_logs"
BACKBONE_ANALYSIS_DIR="$START_DIR/../backbone/"
ORDINAL_ANALYSES_DIR="$START_DIR/../ordinal/"
BACKBONE_TREES_DIR="${START_DIR}/01_backbone_trees/"
ORDINAL_SEQS_DIR="${START_DIR}/02_ordinal_seqs/"
ORDINAL_ALIGNED_DIR="${ORDINAL_SEQS_DIR}/aligned/"
ORDINAL_NOT_ALIGNED_DIR="${ORDINAL_SEQS_DIR}/not_aligned/"
ORDINAL_NOT_ALIGNED_SEQS_DIR="${ORDINAL_NOT_ALIGNED_DIR}/01_seqs/"
ORDINAL_NOT_ALIGNED_ALIGNED_DIR="${ORDINAL_NOT_ALIGNED_DIR}/02_aligned/"
ORDINAL_NOT_ALIGNED_REORIENTED_DIR="${ORDINAL_NOT_ALIGNED_DIR}/03_reoriented_seqs/"
PRE_MERGE_DIR="${START_DIR}/03_pre_merge_aligns/"
ALIGNED_DIR="${START_DIR}/04_merged_aligs/"
CLEANED_ALIGNED_DIR="${START_DIR}/05_cleaned_aligns/"
GENE_TREES_DIR="${START_DIR}/06_gene_trees/"
CONSTRAINTS_DIR="${GENE_TREES_DIR}/constraints"
TREESHRINK_DIR="${START_DIR}/07_treeshrink/"
ASTRAL_DIR="${START_DIR}/08_astral/"
ASTRAL_PATH="$APPS/Astral_mp"
SORTADATE_DIR="${START_DIR}/09_sortadate"
SORTADATE_PATH="$APPS/SortaDate"
CALIBRATION_DIR="${START_DIR}/10_calibrate/"

### FILES
MAFFT_JOBID_PATH="${START_DIR}/mafft_jobid.txt"
FASTTREE_JOBID_PATH="${START_DIR}/fasttree_jobid.txt"
